name: Create reproducible builds for this repo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

env:
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/repro-build

jobs:
  repro-build-push:
    name: ubuntu-${{ matrix.version }}${{ matrix.arch.suffix }} / Docker GHA / ${{ matrix.buildkit.desc }}
    runs-on: ubuntu-${{ matrix.version}}${{ matrix.arch.suffix }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - distro: debian
            version: trixie
            base: trixie-20260112-slim
          - distro: debian
            version: bookworm
            base: bookworm-20260112-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compute image parameters
        id: params
        run: |
          ARCHIVE_DATE=$(date -u +'%Y%m%d')
          SOURCE_DATE_EPOCH=$(date -u -d ${ARCHIVE_DATE} +"%s")
          TAG=${{ matrix.image.version }}-${ARCHIVE_DATE}
          echo "archive_date=${DEBIAN_ARCHIVE_DATE}" >> $GITHUB_OUTPUT
          echo "source_date_epoch=${SOURCE_DATE_EPOCH}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Reproducibly build image
        uses: freedomofpress/repro-build@rewrite
        with:
          tags: ${{ steps.params.tag }}
          file: Dockerfile.${{ matrix.image.distro }}
          platforms: linux/amd64,linux/arm64
          source_date_epoch: ${{ steps.params.source_date_epoch }}
          push: true
          cache: true
